### PR TITLE
Better idea description

### PR DESCRIPTION
**Pull request by tobiastom**
I intentionally made a pull request for this as I did not want to change it just because I think so.

Do we all agree that we do not want to build one concrete linux implementation?

### CODE REVIEW

**Comment by lukasbestle** [comment]
IMHO we should build both: The protocol definitions and a reference implementation based on Linux made for people who want to host their really own GDS.

**Comment by jeena** [comment]
You guys should have a look at https://arkos.io/ which kind of sounds like it could be a reference implementation of the protocol in the future and works already (only on Raspberry Pi and in a different way, but the ideas seem to me quite compatible).

**Comment by datagrok** [comment]
I like the move away from "GDS is an operating system ..." toward "GDS is a collection of applications ..." or "GDS is a reference implementation of an open protocol specification ..."

I already have a box on my home LAN that I use for fileserving etc. Running GDS on it, under the flavor of Linux that I'm familiar with, as an application or collection of applications, is preferable to setting up some kind of virtualization system to host a Linux that I don't have much experience with, or paying for cloud hosting I neither need nor trust.

Knowing that the various components can be replaced with ones I like better (provided they conform to the GDS protocol/specification) also makes adoption easier.

It also hints at the possibility of integration with other efforts, like http://www.freedomboxfoundation.org/

By all means offer, in addition, a reference implementation of the GDS specification pre-installed into a virtual machine image or installable .iso for folks who don't care about these things, or just want to quickly spin up an instance to try out.

**Comment by lukasbestle** [comment]
I don’t think running GDS as an „application“ is possible.
You would have to download an .iso and install it from scratch.

If we have success, you don’t even _want_ to know what happens in the back of the system. It would just work.

**Comment by tobiastom** [comment]
I like the side node about a reference implementation. I've added it.

**Comment by augustl** [comment]
@vis7mac any specific reason you think it's hard to do this as an application? I'm thinking that docker via KVM is pretty awesome stuff :)

**Comment by lukasbestle** [comment]
It is _possible_ but I don’t think we should focus on it because the main focus is the protocol.
If someone wants to implement a GDS application for Windows, for Linux or for whatever, he can do that.

Our main goal is to create and finalize a good concept so other people can implement it.
If _we_ want to implement a specific implementation idea (and which one!) in the future has yet to be decided.

**Comment by anselmh** [comment]
I’d vote for this change as it isn’t that specified and therefore sound more like the idea discussed in our meeting in Nuremberg. It’s more open for the various stated reasons by the others here.

**Comment by jansauer** [comment]
I like the idea of GDS as a open, technology neutral documentation. But without a reference implementation this project won't change much. Having a working core and one or two application would give the project much more momentum.
A implementation is also the best way to find errors and missing parts in the documentation.
:+1:

**Pull request closed without merging**
