### PR TITLE
Added myself to the possible contributed list.

### PR DESCRIPTION
**Pull request by tobiastom**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
YAY, welcome on board :)

**Comment by tobiastom** [comment]
Not even sure if this pull request is correct. In theory I'm not a contributor for now, I'm just interested into helping :)

**Comment by tobiastom** [comment]
Hehe, thanks :)

**Comment by bastianallgeier** [comment]
That's perfect! Don't worry. Thanks btw for the great discussion and ideas after border:none :)

**Comment by tobiastom** [comment]
You're very welcome. There's more where that came from :)

**Pull request merged**
