### PR TITLE
described an app installation integration

### PR DESCRIPTION
**Pull request by timkaechele**
Described an integration of the app installation process

### CODE REVIEW

**Comment by lukasbestle** [comment]
Sounds good, but I would say "new tags", not "new commits". :)

**Comment by timkaechele** [comment]
yeah. totally agree

**Comment by piranna** [comment]
We should reuse existing .json manifest files or format, like npm package.json. They allow to be extended, are mainly not attached to a platform and don't force to add a new manifest file (bower.json? wtf!?)

**Comment by bastianallgeier** [comment]
It's so awesome that you guys started working on the project again and I'm super sorry I have been quiet for so long. I hope I can join soon again.

**Pull request merged**
